manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-keyboard-module-pandawings-i
      url: https://github.com/AkytharPandaaa/zmk-keyboard-module-pandawings-i
      revision: main
      path: modules/zmk-keyboard-module-pandawings-i
    - name: zmk-module-caps-word-de
      url: https://github.com/robertwidfen/zmk-module-caps-word-de.git
      revision: main
      path: modules/zmk-module-caps-word-de
    - name: zmk-locales
      url: https://github.com/joelspadin/zmk-locales.git
      revision: main
      path: modules/zmk-locales
  self:
    path: config
